config/routes.rb
Rails.application.routes.draw do
 
 get 'user', to:'user#show'
 get 'userexpired', to: 'user#expired'

root 'pages#home'

#Computer routes for page display
get 'computer', to:'computer#show'
get 'computerexpired', to:'computer#expired'
end

app/models/computer.rb
class Computer < ActiveRecord::Base



end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/computer_controller.rb
class ComputerController < ApplicationController

	def show

	#@computers = Computer.all
	@tasks_grid = initialize_grid(Computer,
		enable_export_to_csv: true,
  		csv_file_name:'All_Computers')
	end

	def expired
	@q = Computer.ransack({ disabled_eq: 'Yes' }, { auth_object: :admin })
    @computers = initialize_grid(@q.result)
  	end
 end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  
  def show
  
  #@user = User.all
  @tasks_grid = initialize_grid(User)

  end

  def expired
	@q = User.ransack({ disabled_eq: 'Yes' }, { auth_object: :admin })
	@users = initialize_grid(@q.result)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/computer/expired.html.erb
<h1 align = "center">Computer Disabled</h1>

<%= grid(@computers) do |g|

  g.column name: 'Name',attribute: 'computername' do |task|
    task.computername
  end

  g.column name: 'OperatingSystem',attribute: 'operatingsystem'  do |task|
    task.operatingsystem
  end

  g.column name: 'PasswordAge',attribute: 'passwordage' do |task|
    task.passwordage
  end

  g.column name: 'Disabled',attribute: 'disabled' do |task|
    task.disabled
  end

end -%>

app/views/computer/show.html.erb
<h1 align="center">All Active Directory Computer Objects</h1>

<%= grid(@tasks_grid) do |g|

  g.column name: 'Name',attribute: 'computername' do |task|
    task.computername
  end

  g.column name: 'OperatingSystem',attribute: 'operatingsystem'  do |task|
    task.operatingsystem
  end

  g.column name: 'PasswordAge',attribute: 'passwordage' do |task|
    task.passwordage
  end

  g.column name: 'Disabled',attribute: 'disabled' do |task|
    task.disabled
  end

end -%>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%=link_to "Active Directory",root_path,class: "navbar-brand",id: "logo"%>
      </div>



    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Computers <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "All Computers", computer_path %></li>
            <li><%= link_to "Computer Disabled", computerexpired_path %></li>
          </ul>
          </li>
           <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Users <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "All Users", user_path %></li>
            <li><%= link_to "Users Disabled", userexpired_path %></li>
          </ul>
          </li>
      </ul>
      </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ADProject</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/navigation' %>
<div class="container">
<%= yield %>
</div>
<%= debug(params) if Rails.env.development? %>
</body>
</html>

app/views/pages/home.html.erb
<div class="center jumbotron">
<h1 align="center">Active Directroy Query</h1>
</div>

app/views/user/expired.html.erb
<h1 align = "center">User Disabled</h1>

<%= grid(@users) do |g|

  g.column name: 'Name',attribute: 'username' do |task|
    task.username
  end

  g.column name: 'Office',attribute: 'office'  do |task|
    task.office
  end

  g.column name: 'Address',attribute: 'address' do |task|
    task.address
  end

  g.column name: 'Disabled',attribute: 'disabled' do |task|
    task.disabled
  end

end -%>

app/views/user/show.html.erb
<h1 align="center">All Active Directory User Objects</h1>

<%= grid(@tasks_grid) do |g|

  g.column name: 'Name',attribute: 'username' do |task|
    task.username
  end

  g.column name: 'Office',attribute: 'office'  do |task|
    task.office
  end

  g.column name: 'Address',attribute: 'address' do |task|
    task.address
  end

  g.column name: 'Disabled',attribute: 'disabled' do |task|
    task.disabled
  end

end -%>